name:  Test Providers

on:
  workflow_dispatch:  

jobs:
  Test-Providers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          rm -f pnpm-lock.yaml
          pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test Anilist
        run: pnpm test-anilist

      - name: Test Jikan
        run: pnpm test-jikan

      - name: Test Hianime
        run: pnpm test-hianime

      
      # - name: Test Animekai
      #   run: pnpm test-animekai

      - name: Test FlixHQ
        run: pnpm test-flixhq

      - name: Test TMDB
        run: pnpm test-tmdb  

      - name: Test TvMaze
        run: pnpm test-tvmaze 

     
  
